
GET http://localhost:3000/api/todos

###
GET http://localhost:3000/api/todos/652b944232e53c0008ec13cf

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
	"name": "meysam"
}

###
DELETE http://localhost:3000/api/todos/652b944232e53c0008ec13cf

###
PATCH  http://localhost:3000/api/todos/652e5146718954156f7acf21
Content-Type: application/json

{
	"name": "ms"
}
