
GET http://localhost:3000/api/todos

###
GET http://localhost:3000/api/todos/653d36ba2f97c285577efbef

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
	"name": "new name"
}

###
DELETE http://localhost:3000/api/todos/653e0d55c706222eec61cd87

###
PATCH  http://localhost:3000/api/todos/653e0cfcc706222eec61cd85
Content-Type: application/json

{
	"name": "chasdfas",
	"isDone": true
}
