
GET http://localhost:3000/api/todos

###
GET http://localhost:3000/api/todos/653d46df9a6a204999fa3fd5

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
	"name": "msm-faraj"
}

###
DELETE http://localhost:3000/api/todos/653e16e268a57e6a253874d3

###
PATCH  http://localhost:3000/api/todos/653d46df9a6a204999fa3fd5
Content-Type: application/json

{
	"name": "msm-faraj",
	"isDone": true
}
